# reference guide => https://docs.github.com/en/actions/learn-github-actions

name: ci-tenant-exports-queue

on: ['push']

jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      # download the files to inside environment
      - name: Checkout Code 
        uses: actions/checkout@v3 
        id: checkout

      # reference => https://github.com/actions/setup-node
      - name: Set Up Node.js
        id: setup-node
        uses: actions/setup-node@v4 
        with:
          node-version: 18
      
      - name: Install Dependencies
        id: install
        run: npm ci
      
      - name: Test Code
        id: test
        run: npm test